[project]
name = "python-sdia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipynb>=0.5.1",
    "nbimporter>=0.3.4",
    "notebook>=7.4.5",
    "pytest>=8.4.2",
]
